name: pywicta-dev
channels:
  - jdhp
  - cta-observatory
  - conda-forge
dependencies:
  - ctapipe
  - ctapipe-extra=0.2.*
  - ipython
  - ipywidgets
  - cython
  - jupyter
  - notebook
  - docutils
  - pep8
  - pytest
  - pytest-cov
  - readline
  - setuptools
  - sphinx
  - sphinx_rtd_theme
  - sphinx-automodapi
  - sphinxcontrib
  - sphinxcontrib-websupport
  - traitlets
  - wheel
  - xz
  - yaml
  - zlib
  - numpy
  - numpydoc
  - scipy
  - scikit-image
  - pillow
  - astropy
  - pandas
  - matplotlib
  - bokeh
  - gammapy
  - graphviz
  - iminuit
  - numba
  - pyhessio
  - psutil
  - scikit-learn
  - pytables  
  - tqdm
  - pip:
      - pytest_runner
      - pywi
